apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: announcements
  namespace: nais
spec:
  accessPolicy:
    outbound:
      external:
        - host: nais.io
        - host: slack.com
  env:
    - name: SLACK_CHANNEL_ID
      value: "C01DE3M9YBV"
  image: {{image}}
  ingresses:
    - https://announcements.external.prod-gcp.nav.cloud.nais.io
  port: 8080
  observability:
    logging:
      destinations:
        - id: loki
  envFrom:
    - secret: announcements
  valkey:
    - access: readwrite
      instance: rss
