apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: announcements
  namespace: nais
spec:
  image: {{image}}
  ingresses:
    - https://announcements.external.prod-gcp.nav.cloud.nais.io
  port: 8080
  envFrom:
    - secret: announcements
  valkey:
    - access: readwrite
      instance: rss
